### ISSUE TITLE
YouTube channel for iojs TC mettings

### ISSUE THREAD

**Issue by techjeffharris** [iojs/roadmap#10]
First, I would like to say thanks for all your work! Its been fun to watch this project develop :)

Second, I know that its not hard to search the github issues for links to YouTube streams of the TC meetings, but I would like to propose a YouTube channel for TC meetings as its not so straight-forward to find them from the YouTube search.

**Comment by mikeal** [comment]
I think there is one already, I probably need to move the older ones over to it.

**Comment by techjeffharris** [comment]
I'm not able to find it, would you mind providing a link, please?

**Comment by iancrowther** [comment]
link oud be great, they are spread all over atm.

**Comment by mikeal** [comment]
You know what, there isn't one.

I can't create one because my account is already linked to one. That said, we could post these in the "JSConf" channel, which is full of like every conference work going to :) We could create a playlist and tag for io.js in there :)

**Comment by mikeal** [comment]
Also, JSConf already has 24K subscribers :)

**Comment by mikeal** [comment]
I'm in the middle of transferring all the videos in my account to JSConf and a new playlist. Hopefull @rvagg can do the same :)

**Comment by mikeal** [comment]
https://www.youtube.com/playlist?list=PL37ZVnwpeshFu8NoKFT0Hn0H_ECAIsIAW

**Comment by iancrowther** [comment]
great, thanks - will be sure to broadcast via LNUG

**Comment by iancrowther** [comment]
https://twitter.com/LNUGorg/status/555467271179866112

**Comment by techjeffharris** [comment]
cool, thanks!

**Comment by techjeffharris** [comment]
"[Deleted Video]" for all five videos :'(

**Comment by rvagg** [comment]
https://www.youtube.com/channel/UC9Ug4jAzdP-T3ozwjpL9BYw

we have an io.js google plus page now and they are going in the YouTube channel for that. I'll be uploading mine shortly.

**Comment by techjeffharris** [comment]
You rock, @rvagg!  Thank you!

**Comment by mikeal** [comment]
sorry, forgot to post here that I had to move them, again, but now we have our own io.js channel :) thanks @rvagg for filling in :)

**Comment by techjeffharris** [comment]
oops, got excited.  just realized that @rvagg's videos aren't in there yet, so i'll reopen.

**Comment by mikeal** [comment]
closing for now, i'll continue to bug @rvagg to push his old videos but moving forward all the calls will be on this channel :)

**Comment by techjeffharris** [comment]
Cheers! Thanks :-)
