### ISSUE TITLE
Node.js capitalization

### ISSUE THREAD

**Issue by bnb** [iojs/roadmap#19]
Should `node.js` be capitalized on Slide 2? I've always thought the standard was to capitalize it.

**Comment by mikeal** [comment]
I don't think so, they are used interchangably and it makes it uniform with `io.js`.

**Comment by rvagg** [comment]
I always opt for "Node.js" fwiw

**Comment by mikeal** [comment]
it just looks weird wehn we don't capitalize io.js

**Comment by rvagg** [comment]
I feel the same weirdness when I don't capitalise "npm" but I suck it up

**Comment by bnb** [comment]
Yeah, I always go to capitalize NPM  but then remember and delete it. io.js and Node.js looks fine to me, but if they're both officially/commonly allowed/used, then I guess it's okay.
