### ISSUE TITLE
Define "already" in slide 3

### ISSUE THREAD

**Issue by bnb** [iojs/roadmap#20]
> io.js is a community driven open source project. It was started by the primary contributors to node.js but **has already attracted** more active developers than the node.js project has had in its entire history.

There's no context with "already," which leaves it ambiguous as to how successful io.js is. I would write 

> ...but in just a few months has attracted...

> ...but in a very short time has attracted...

> ...but in a few months has attracted...

> ...but since August (?), 2014, has attracted...

> ...but since August (?) has attracted ...

**Comment by mikeal** [comment]
Being this specific puts us in the unfortunate situation of updating this document all the time and then getting translators to do the same :(

**Comment by bnb** [comment]
@mikeal I think these two (modified) comments would be okay in that respect

> ...but in a few months attracted...
^ This limits to a certain timeframe, and removes the past-up-to-present tense "had," which itself would limit future use.
> ...but since August, 2014, attracted...
^ This gives a specific start time, giving an exact frame of reference for the reader. A few words would need to be updated to increase magnitude of the active developers as time goes on, but less than the other options I presented. 

With regard to how it's currently worded, it's not future proofed as-is. If someone presents this in 10 months, it will read clearly as older and/or outdated. 

I think a major limiting factor are the words "has" and "already," which refer to the time period from the start of the project to now. Modularizing the statement, making it independent of time, is what will fix the updating problem.

**Comment by mikeal** [comment]
how about `... in the first few months ....`

**Comment by bnb** [comment]
Sounds good.

**Comment by mikeal** [comment]
fixed.
