### ISSUE TITLE
"NG repo"

### ISSUE THREAD

**Issue by bnb** [iojs/roadmap#21]
On the Next Generation side, it says

> NG discussions are ongoing in the NG repo.

With NG Repo linking to #14 in this repository. The previous slide also links to the exact same page. I would also say it is a bit misleading/discouraging to say NG discussions are going on in the NG repo, and then link to a _closed_ issue.

**Comment by mikeal** [comment]
Fixed, there *is* an NG repo :)

**Comment by bnb** [comment]
@mikeal Awesome, thanks.
