### ISSUE TITLE
Stability Policy status & links

### ISSUE THREAD

**Issue by bnb** [iojs/roadmap#22]
Two pages have links titled "Stability Policy"--the LTS slide and the Stability Policy slide. Both link to a closed issue. The Stability Policy slide says it's still under development, and the LTS slide says there's a draft. I looked at the issue the LTS slide links to, and it looks like the draft was merged into the main io.js repo 3 minutes previous to writing this post. Do these slides need to be updates? It seems quite likely that they do.

**Comment by mikeal** [comment]
It's actually part of the roadmap now, which was just merged, I guess all of those need to get updated.

**Comment by mikeal** [comment]
Ok, fixed the links :)
