### ISSUE TITLE
Suggestions for naming...

### ISSUE THREAD

**Issue by tracker1** [iojs/roadmap#5]
Previously someone had suggested in another thread about having `io` be the main bin executable and `npm` as-is...

I was thinking that (like perl, ruby, etc..) the main executable should simply be `js` or `/bin/js` in *nix systems.  And that `jspm` simply be a script that runs `npm` out of the npm repository... (where the installation will install the `js` executable, as well as the npm (inside npm's install itself), then link or create a run script that points to the current version.

Just thinking that `js` really is the language, and should simply be where it is... one other minor opinion, is that we should stop hiding new features behind --harmony flags...  Especially what's been established for ES6.

**Comment by rvagg** [comment]
TC resolution on this is something like this: project name is "io.js", binary is "iojs" with a symlink (or possibly a mini redirecting executable in the case of Windows) to "node". Maybe using the "alternatives" system on various Linux distributions to work with Node.js releases.
